mysocial/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from social import views

urlpatterns = [
                  path("", views.index, name="index"),
                  path('logout/', views.logout_user, name='logout'),
                  path('signup/', views.signup, name='signup'),
                  path('admin/', admin.site.urls),
                  path('login/', views.login_view, name='login'),
                  path('', include('allauth.urls')),
                  path('auth/', include('allauth.socialaccount.urls')),
                  path('create_post/', views.create_post, name='create_post'),
                  path('uploadData/<str:username>/', views.upload_profile_image, name='upload_profile_image'),
                  path('displayProfile/', views.display_profile, name='display_profile'),
                  path('startPost/', views.start_post, name='startPost'),
                  path('userPost/<int:user_id>/', views.all_user_posts, name='userPost'),
                  path('display_posts/<int:user_id>/', views.display_posts, name='display_posts'),
                  path('display_posts/', views.display_posts, name='display_posts'),
                  path('unfriend/<str:username>/', views.unfriend, name='unfriend'),
                  path('userPost/', views.all_user_posts, name='userPost'),
                  path('friends_list/', views.friends_list, name='friends_list'),
                  path('sent_request/', views.count_friend_requests_sent, name='sent_request'),
                  path('reject_friend_request/<int:request_id>/', views.reject_friend_request,
                       name='reject_friend_request'),
                  path('accept_friend_request/<int:request_id>/', views.accept_friend_request,
                       name='accept_friend_request'),
                  path('friend_requests/', views.received_friend_requests, name='friend_requests'),
                  path('send_friend_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
                  path('any_profile_view/<int:user_id>/', views.any_profile_view, name='any_profile_view'),
                  path('', RedirectView.as_view(url='/')),
                  re_path(r'^.*/$', RedirectView.as_view(url='/')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/models.py
from enum import unique, IntEnum

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True)
    location = models.CharField(null=False, default='unknown', max_length=10)
    profile_image = models.ImageField(upload_to='images/', null=True, blank=True)
    phn_num = models.CharField(max_length=10, default='0000000000')
    gender = models.CharField(max_length=10, null=False, default='unknown')
    school = models.CharField(max_length=100, null=False, default='unknown')
    bio = models.TextField(blank=True)
    interest = models.CharField(max_length=100, null=False, default='unknown')
    friends = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return self.user.username

    def temp_col(self):
        return f"{self.dob} {self.gender}"


class UserPost(models.Model):
    username = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)  # Automatically set to the current date
    time = models.TimeField(default=timezone.now)  # Automatically set to the current time
    caption = models.CharField(max_length=250, null=True)
    files = models.ImageField(null=False, upload_to='images/')


class FriendRequest(models.Model):
    from_user = models.ForeignKey(UserProfile, related_name='sent_friend_requests', on_delete=models.CASCADE)
    to_user = models.ForeignKey(UserProfile, related_name='received_friend_requests', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"From: {self.from_user}, To: {self.to_user}"

social/forms.py
from django import forms
from .models import UserPost, UserProfile


class UserPostForm(forms.ModelForm):
    class Meta:
        model = UserPost
        fields = ['caption', 'files']  # Specify the fields you want to include in the form
        labels = {
            'files': 'File',  # Customize the label for the 'files' field
        }


class UserProfileForm(forms.ModelForm):
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    class Meta:
        model = UserProfile
        fields = ['dob', 'location', 'profile_image', 'phn_num', 'gender', 'school', 'bio', 'interest']
        widgets = {
            'dob': forms.widgets.DateInput(attrs={'type': 'date'})
        }

social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_exempt
import facebook
from mysocial.settings import FACEBOOK_ACCESS_TOKEN
from social.models import UserProfile, UserPost, FriendRequest
from datetime import datetime
from django.utils import timezone
from django.contrib import messages
from .forms import UserProfileForm
from .forms import UserPostForm
from django.contrib.auth.decorators import login_required


@login_required()
def logout_user(request):
    logout(request)
    return redirect('login')


def count_friend_requests_sent(request):
    logged_user = UserProfile.objects.get(user=request.user)
    friend_requests_sent = FriendRequest.objects.filter(from_user=logged_user)
    friend_requests_sent = reversed(friend_requests_sent)
    return render(request, 'count_friend_requests.html', {'friend_requests_sent': friend_requests_sent})


@login_required
def unfriend(request, username):
    user_profile = UserProfile.objects.get(user=request.user)
    friend_to_unfriend = UserProfile.objects.get(user__username=username)

    user_profile.friends.remove(friend_to_unfriend)

    return redirect('/friends_list')


def create_post(request):
    if request.method == 'POST':
        form = UserPostForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = request.user.userprofile
            new_post = form.save(commit=False)
            new_post.username = user_profile
            new_post.save()
            return redirect('/display_posts')  # Redirect to a page that displays all posts after successful submission
    else:
        form = UserPostForm()
    return render(request, 'create_post.html', {'form': form})


def display_posts(request, user_id=None):
    facebook_access_token = FACEBOOK_ACCESS_TOKEN
    graph = facebook.GraphAPI(access_token=facebook_access_token)

    # graph = facebook.GraphAPI(access_token)
    posts = graph.get_connections('me', 'feed')['data']
    facebook_posts = [
        {
            'url': f'https://www.facebook.com/{post["id"]}',
            'width': 500,
            'show_text': True,
        }
        for post in posts
    ]
    user = request.user
    if user_id is None:
        all_posts = UserPost.objects.filter(username__user=user)
        user_view = request.user.username
    else:
        all_posts = UserPost.objects.filter(username_id=user_id)
        curr = UserProfile.objects.get(pk=user_id)
        user_view = curr.user.username
    all_posts = reversed(all_posts)
    if request.method == 'POST':
        post_id_to_delete = request.POST.get('post_id_to_delete')
        if post_id_to_delete:
            # Delete the post if the logged-in user is the owner of the post
            post_to_delete = get_object_or_404(UserPost, id=post_id_to_delete, username__user=user)
            post_to_delete.delete()
            return redirect('display_posts')
    return render(request, 'display_posts.html',
                  {'all_posts': all_posts, 'fb_post': facebook_posts, 'user_view': user_view})


def upload_profile_image(request, username=None):
    user, created = User.objects.get_or_create(username=username)
    visible = True
    try:
        user_profile = UserProfile.objects.get(user=user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile(user=user)
        visible = False

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('display_profile')
    else:
        form = UserProfileForm(instance=user_profile)

    return render(request, 'upload_profile_image.html', {'form': form, 'visible': visible})


def index(request):
    return render(request, "index.html")


def any_profile_view(request, user_id=None):
    user = get_object_or_404(UserProfile, pk=user_id)
    user_posts = UserPost.objects.filter(username=user).count()
    users = UserProfile.objects.all().exclude(user=request.user)
    curr_user = UserProfile.objects.get(user=request.user)
    all_friends = curr_user.friends.all()
    req_from = UserProfile.objects.get(user=request.user)
    all_req = FriendRequest.objects.filter(from_user=req_from)
    only_to_user = [req.to_user for req in all_req]
    res_query = list(all_friends) + list(only_to_user)

    res = False
    curr_search = ""
    user_idd = ""
    if request.method == 'POST':
        curr_search = request.POST.get('searchForm')
        if request.POST.get('searchForm'):
            try:
                user_u = User.objects.get(username=curr_search)
                user_pro = UserProfile.objects.get(user=user_u)
                user_idd = user_pro.id
            except User.DoesNotExist or UserProfile.DoesNotExist:
                user_idd = None
            for s_user in users:
                temp = str(s_user.user)
                if temp == curr_search:
                    res = True
                    break
                else:
                    res = False
            if not res:
                curr_search = "User Not Found"
        elif user_posts > 0 and request.POST.get('all'):
            return redirect(f'/display_posts/{user_id}')

        elif request.POST.get('add_button'):
            selected_user = request.POST.get('add_button')
            user = User.objects.get(username=selected_user)
            user_profile = UserProfile.objects.get(user=user)
            user_id = user_profile.pk
            to_user = UserProfile.objects.get(pk=user_id)
            from_user = UserProfile.objects.get(user=request.user)
            existing_request = FriendRequest.objects.filter(from_user=from_user, to_user=to_user).first()

            # Check if users are already friends
            if from_user.friends.filter(pk=user_id).exists():
                messages.warning(request, f'You are already friends with {to_user.user}.')
                return redirect('/displayProfile')

            # Check if a friend request already exists
            elif existing_request:
                messages.warning(request, 'Request is already sent.')
                return redirect('/displayProfile')
            else:
                messages.success(request, 'Request sent.')
                return redirect(f'/send_friend_request/{user_id}/')

    context = {
        'user_profile': user,
        'all_user': users,
        'all_post': user_posts,
        'found': res,
        'search': curr_search,
        'user_id': user_idd,
        'disable': True,
        'isSent': False,
        'sugg': True,
        'isFriend': res_query,
        'isHome': True,
        'myProfile': "User"
    }
    return render(request, 'displayProfile.html', context)


@login_required
def send_friend_request(request, user_id):
    to_user = UserProfile.objects.get(pk=user_id)
    from_user = UserProfile.objects.get(user=request.user)

    friend_request = FriendRequest(from_user=from_user, to_user=to_user)
    friend_request.save()
    # return redirect(f'/any_profile_view/{user_id}')
    return redirect('/displayProfile')


@login_required
def received_friend_requests(request):
    logged_user = UserProfile.objects.get(user=request.user)
    received_requests = FriendRequest.objects.filter(to_user=logged_user)
    if not received_requests:
        return HttpResponseRedirect('/displayProfile')
    return render(request, 'received_requests.html', {'received_requests': received_requests})


def reject_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, pk=request_id)
    logged_user = UserProfile.objects.get(user=request.user)

    if logged_user == friend_request.to_user:
        friend_request.delete()
        messages.success(request, f'Friend request from {friend_request.from_user.user.username} has been rejected.')

    return redirect('display_profile')


@login_required
def accept_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, pk=request_id)
    logged_user = UserProfile.objects.get(user=request.user)

    if logged_user == friend_request.to_user:
        friend_request.from_user.friends.add(friend_request.to_user)
        friend_request.to_user.friends.add(friend_request.from_user)

        friend_request.delete()
    return redirect('friend_requests')


@login_required
def all_user_posts(request, user_id=None):
    user = request.user
    date = timezone.now().date()
    if user_id is None:
        user_all_posts = UserPost.objects.filter(username__user=user)
    else:
        user_all_posts = UserPost.objects.filter(username_id=user_id)

    user_all_posts = reversed(user_all_posts)  # to display posts in latest order of addition
    return render(request, "allPosts.html", {'user_all_posts': user_all_posts, 'user': user, 'date': date})


def start_post(request):
    username = request.user
    date = timezone.now().date()
    time = timezone.now().time()
    user_profile = UserProfile.objects.get(user=username)

    if request.method == 'POST':
        caption = request.POST.get('caption')
        file = request.POST.get('post_file')

        newpost = UserPost()
        newpost.username = user_profile
        newpost.date = date
        newpost.time = time
        newpost.caption = caption
        newpost.files = file

        newpost.save()
        return redirect('/userPost')

    context = {
        'username': username,
    }
    return render(request, "createPost.html", context)


def friends_list(request):
    user_profile = UserProfile.objects.get(user=request.user)
    friends = user_profile.friends.all()
    return render(request, 'friendList.html', {'friends': friends})


# @login_required
def display_profile(request):
    try:

social/templates/allPosts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>User Posts</title>
    <style>
        .post-grid {
            display: flex;
            flex-wrap: wrap;
        }

        .post-item {
            flex: 1 0 25%; /* Each post will take up 25% of the available width */
            padding: 10px;
            box-sizing: border-box;
        }

        .post-container {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 20px;
            background-color: #efecec;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

       .post-image {
            width: 100%;
            height: auto;
            max-height: 150px;
            transition: transform 0.5s ease-in-out;
        }

        /* Zoom-in effect on hover */
        .post-image:hover {
            transform: scale(1.5);
        }
    </style>
</head>
<body>
    <h3>Posts</h3>
    <div class="post-grid">
        {% for post in user_all_posts %}
            <div class="post-item">
                <div class="post-container">
                    <strong>Posted by:</strong> {{ user}}<br>
                    <strong>{{ date }}</strong>
                    <div>
                        <strong>{{ post.caption }}</strong>
                    </div>
                    <br>
{#                    {% if post.post_file %}#}
                        <img class="post-image" src="{{ post.files.url }}" alt="Post Image">
{#                    {% endif %}#}
                </div>
            </div>
        {% endfor %}
    </div>

</body>
</html>

social/templates/anyProfileView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends 'navBar.html' %}

    {% block content %}
        <h1>{{ user.username }}'s Profile</h1>

        <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.bio }}</p>

        <a href="{% url 'friend_requests' %}">Friend Requests</a>
{#        <a href="{% url 'edit_profile' %}">Edit Profile</a>#}
    {% endblock %}
</body>
</html>

social/templates/count_friend_requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Friend Requests Sent</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .header {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
            color: #2b60e7;
        }

        .friend-request {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 10px;
            background-color: #f0f0f0;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.17        );
        }

        .friend-request p {
            margin: 5px 0;
        }

        .no-requests {
            text-align: center;
            font-size: 20px;
            color: #777;
        }

        .friend-request strong {
            color: #45cc4a;
        }
    </style>
</head>
<body>
{% extends 'navBar.html' %}
{% block navbar %}
        <div class="navbar">
            <a href="/">Home</a>
{#            <a href="{% url 'upload_profile_image' username=user_profile.user.username %}">Edit</a>#}
            <a href="/displayProfile">Profile</a>
            <a href="{% url 'logout' %}">Logout</a>
        </div>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="header">Friend Requests Sent</div>
        {% if friend_requests_sent %}
            {% for request in friend_requests_sent %}
                <div class="friend-request">
                    <p><strong>Friend Request Sent to:</strong> {{ request.to_user.user }}</p>
                    <p><strong>Date Sent:</strong> {{ request.created_at }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p class="no-requests">No friend requests sent yet.</p>
        {% endif %}
    </div>
{% endblock %}
</body>
</html>

social/templates/create_post.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Create New Post</title>
    <style>
/* Add your custom CSS styles here */

/* Body styles */
body {
    font-family: Arial, sans-serif;
    background-color: #f9f9f9;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

/* Form container styles */
.form-container {
    background-color: #f0f0f0;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
    max-width: 400px;
    width: 100%;
}

/* Heading styles */
h2 {
    text-align: center;
    color: #2f47ec;
    margin-top: 4px;
    margin-bottom: 20px;
}

/* Label styles */
label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
    color: #333;
}

/* Input styles */
input[type="text"],
input[type="date"],
input[type="file"],
input[type="tel"],
textarea {
    width: 90%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 10px;
    background-color: white;
     box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    font-size: 15px;
    transition: border-color 0.3s ease-in-out;
}

/* Input focus styles */
input[type="text"]:focus,
input[type="date"]:focus,
input[type="file"]:focus,
input[type="tel"]:focus,
textarea:focus {
    outline: none;
    border-color: #3f42e8;
}

/* Radio button styles */
input[type="radio"] {
    margin-right: 5px;
    vertical-align: middle;
}

/* Submit button styles */
button[type="submit"] {
    background-color: #007bff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
     box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
    font-size: 16px;
    width: 100%;
    transition: background-color 0.3s ease-in-out;
}

/* Submit button hover styles */
button[type="submit"]:hover {
    background-color: #03468d;
    transition: background-color 0.3s ease-in-out;
}

/* Radio label styles */
.radio-label {
    display: inline-block;
    margin-right: 10px;
}

    </style>
</head>
<body>
    <div class="form-container">
        <h2>Create New Post</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create Post</button>
        </form>
    </div>
</body>
</html>

social/templates/display_posts.html
<html>
<head>
    <title>All Posts </title>
    <style>
        .post-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr); /* Four columns per row */
            grid-gap: 20px; /* Gap between grid items */
            margin: 4px 8px;
        }

        .post-item {
            display: flex;
            flex-wrap: wrap;
            border: 1px solid #ccc;
            padding: 10px;
            border-radius: 5px;
            background-color: #f0f0f0;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .post-container {
            display: flex;
            flex-direction: column;
            margin-bottom: 10px;
        }

        .post-image {
            /* Style for the post image */
            width: 100%;
            margin: 0 auto;
            height: auto;
            object-fit: cover;
            max-height: 250px;
            border-radius: 9px;
            transition: transform 0.5s ease-in-out;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
        }

        .post-image:hover {
            transform: scale(1.08);
        }

        .btn {
            background-color: #f14755;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 14px;
            cursor: pointer;
            font-size: 16px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }

        button:hover {
            background-color: #af0606;
            color: white;
        }

        .left {
            flex: 1;
            position: relative;
            z-index: 1;
            max-width: 300px;
            max-height: 300px;
            float: left;
            margin: 0 auto;
            padding: 15px;
            background-color: #eee5e5;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        }

        .right {
            flex: 1;
            padding-left: 20px;
            position: relative;
            z-index: 1;
        }

        .grid {
            display: flex;
            justify-content: stretch;
        }

        @media (max-width: 768px) {
            .post-grid {
                grid-template-columns: repeat(2, 1fr); /* Two columns per row for small screens */
            }

            .post-item {
                padding: 5px; /* Adjust padding for small screens */
            }

            .post-image {
                max-height: 150px; /* Reduce image height for small screens */
            }
        }

        @media (max-width: 576px) {
            .post-grid {
                grid-template-columns: repeat(1, 1fr);
            }
        }

        .post-item .left {
            max-height: 800px;
            max-width: 200px;
        }

        .over {
            flex: 1 100%;
            word-break: break-word;
        }

        .fb-like {
            margin-top: 10px;
        }
    </style>
</head>
<body>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v18.0&appId=190534194145117"
        nonce="hniFBzT5"></script>
{% extends 'navBar.html' %}
{% block navbar %}
    <div class="navbar">
        <a href="/">Home</a>
        <a href="/displayProfile">Profile</a>
        <a href="{% url 'logout' %}">Logout</a>
    </div>
{% endblock %}
{% block content %}
    <h2>All Posts of {{ user_view }}</h2>
    <div class="post-grid">
        {% for post in all_posts %}
            <div class="post-item">
                <div class="post-container">
                    <div class="grid">
                        <div class="left">
                            <div>
                                <strong>Posted by:</strong> {{ post.username.user }}<br>
                                <strong>Date:</strong> {{ post.date }}<br>
                            </div>
                            <div class="over">
                                {{ post.caption }}
                            </div>
                        </div>
                        <div class="right">
                            {% if post.username.user == user %}
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="post_id_to_delete" value="{{ post.id }}">
                                    <button type="submit" class="btn">Delete</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                    <br>
                    {% if post.files %}
                        <img class="post-image" src="{{ post.files.url }}" alt="Post Image">
                    {% endif %}
                    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width=""
                         data-layout="standard" data-action="like" data-size="small" data-share="true"></div>
                </div>
            </div>
        {% endfor %}
        {% for post in fb_post %}
            <div class="post-item">
                <div class="post-container">
                    <div class="fb-post" data-href="{{ post.url }}" data-width="{{ post.width }}"
                 data-show-text="{{ post.show_text|yesno:'true,false' }}"></div>
                    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width=""
                         data-layout="standard" data-action="like" data-size="small" data-share="true"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>

social/templates/profileError.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if error %}
        <p class="error-message animate">{{ error }}</p>
    {% endif %}
</body>
</html>

social/templates/upload_profile_image.html
<!DOCTYPE html>
<html>
<head>
    <title>Profile Input Form</title>
    <style>
.form-container {
    background-color: #ececec;
    padding: 10px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    max-width: 400px;
    width: 100%;
    margin: 0 auto; /* Center the form horizontally */
}

/* Heading styles */
h2 {
    text-align: center;
    color: #684aee;
    margin-top: 4px;
    margin-bottom: 5px;
}

#id_location{
    height: 25px;
}
#id_bio{
    height: 25px;
}

/* Label styles */
label {
    display: block;
    margin-bottom: 5px;
    margin-top: 2px;
    font-weight: bold;
    color: #333;
}

/* Input styles */
input[type="text"],
input[type="date"],
input[type="file"],
input[type="tel"],
textarea {
    width: 90%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 8px;
    font-size: 15px;
    transition: border-color 0.3s ease-in-out;
}

/* Input focus styles */
input[type="text"]:focus,
input[type="date"]:focus,
input[type="file"]:focus,
input[type="tel"]:focus,
textarea:focus {
    outline: none;
    border-color: #3f42e8;
}

/* Radio button styles */
input[type="radio"] {
    margin-right: 5px;
    vertical-align: middle;
}
textarea {
    height: 50px; /* Adjust the height as desired */
}

/* Submit button styles */
button[type="submit"] {
    background-color: #007bff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
    width: 100%;
    transition: background-color 0.3s ease-in-out;
}

/* Submit button hover styles */
button[type="submit"]:hover {
    background-color: #03468d;
    transition: background-color 0.3s ease-in-out;
}

/* Radio label styles */
.radio-label {
    display: inline-block;
    margin-right: 10px;
}
p.error-message {
            color: red;
            position: absolute;
            top: 80px;
            left: 44%;
            display: block;
            margin: 0;
            opacity: 0;
            animation: fadeIn 0.5s ease-in-out;
            animation-fill-mode: forwards;
        }
    </style>
</head>
<body>
{% extends 'navBar.html' %}

{% block navbar %}
        <div class="navbar">
            <a href="/">Home</a>
{#            <a id="profile-link" href="{% url 'display_profile' %}?profile_clicked=true">Profile</a>#}
            {% if visible %}
                <a href="/displayProfile">Profile</a>
            {% endif %}
{#            <form method="post"  >#}
{#                {% csrf_token %}#}
{#                <a href="/displayProfile">#}
{#                <button name="profile" type="submit" value="">Profile</button>#}
{#                </a>#}
{#            </form>#}
            <a href="{% url 'logout' %}">Logout</a>
        </div>
{% endblock %}

{% block content %}
    <div class="content">
        {% if clicked and not visible %}
            <div class="error-message">{{ message }}</div>
    {% endif %}
    <form class="form-container" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Profile Input</h2>
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    </div>
{% endblock %}
</body>
</html>